on:
  push:
    branches:
      - test2
jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check diff
        run: git diff origin/main HEAD --exit-code
