on:
  push:
    branches:
      - test2
jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-latest
    steps:
      - name: config main branch
        run: git config --global init.defaultBranch main
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        run: git checkout HEAD^
      - name: Check diff
        run: git diff main HEAD --exit-code
